const EN = {
  administration: "administration",
  allEvents: "all events",
  alreadyTakenPlaces: "booked places",
  authentication: "authentication",
  bankCard: "bank card",
  birthday: "birthday",
  buyTicket: "buy a ticket",
  buyTicketDescriptionMessage: "proceed to the payment of the amount indicated below on one of the numbers (merchant code) according to your mobile operator. Use the code you will receive by SMS in the field provided to obtain your ticket.",
  confirmPassword: "confirm password",
  cancel: "cancel",
  changeLoginInformations: "change login informations",
  checkExceeding: "accept more people than expected",
  city: "city",
  createAccount: "create an account",
  createCode: "generate a code",
  createdAt: "created on",
  createdBy: "created by",
  createTicketMessageSuccess: "your ticket has been successfully created. Please find it in the 'Tickets' area of your account.",
  code: "code",
  codeGenerationMessage: "you have just generated a code. Be sure to pass this information to the buyer of a ticket",
  codeMarchand: "seller code",
  country: "country",
  currencies: "currencies",
  date: "date",
  dateBuy: "bought on",
  delete: "delete",
  description: "description",
  details: "details",
  email: "e-mail",
  errorMessageAuthentication: "authentification error. This session has expired, please log back in",
  errorMessageLogin: "please enter your login and password",
  errorMessageLogin2: "incorrect login or password",
  errorMessageLogin3: "unable to connect. Please make sure you are connected to the Internet",
  errorMessageLockRevision: "changes on the same item were made from another post. Please reload the page to get the latest version.",
  errorMessageNetwork: "please make sure you are connected to the Internet.",
  errorMessageCodeGeneration: "an error occurred while generating a code. Please retry later.",
  errorRegister2: "error while creating your account. The login has already been used by another user.",
  errorRegister3: "error while creating your account. Please make sure you are connected to the Internet.",
  errorMessageTicketCreateWithCode: "an error occurred while creating your ticket. The code you are using can't create this ticket or it has already been used.",
  errorOccurredMessage: "an error occurred while performing this operation. Please retry later.",
  errorMessageNotYourEvent: "you do not have the right to scan this ticket. The affected event belongs to another user.",
  eventCode: "identification",
  eventName: "title",
  events: "events",
  eventDetail: "event details",
  firstname: "firstname",
  getTicket: "get a ticket",
  image: "image",
  invalidForm: "some fields are not valid",
  language: "language",
  lastname: "lastname",
  login: "login",
  manualPayment: "using a code",
  modify: "modify",
  myEvents: "my events",
  noTicketEventFound: "no events found matching this ticket. Maybe the event was deleted.",
  noUserFound: "no users matching this search",
  numero: "number",
  oldPassword: "old password",
  oldPasswordWrong: "the old password is wrong",
  operator: "operator",
  password: "password",
  phone: "phone",
  phones: "phones",
  price: "price",
  priceType: "type",
  profile: "profile",
  register: "register",
  remainingPlaces: "remaining places",
  road: "road",
  save: "save",
  signIn: "sign in",
  signOut: "sign out",
  scan: "scan",
  scanMessageSuccess: "the validation of the ticket has been successfully completed. Please inform the customer that their ticket can no longer be used.",
  search: "search",
  seller: "i am a seller",
  settings: "settings",
  statistics: "statistics",
  successRegister: "welcome to the BYT platform. Your account creation has been successfully completed. You can access your account using the login and password created",
  tag: "tag",
  tickets: "tickets",
  ticketUsed: "used",
  time: "time",
  totalPlaces: "total places",
  usedAt: "used on",
  usedBy: "used by",
  userSearch: "search user",
  userUpdateSuccess: "the update of the information has been carried out successfully.",
  validate: "validate",
  venue: "venue"
}

export { EN };