const EN = {
  administration: "administration",
  authentication: "authentication",
  birthday: "birthday",
  confirmPassword: "confirm password",
  cancel: "cancel",
  createAccount: "create account",
  code: "code",
  email: "e-mail",
  errorMessageAuthentication: "authentification error. This session has expired, please log back in",
  errorMessageLogin: "please enter your login and password",
  errorMessageLogin2: "incorrect username or password",
  errorMessageLogin3: "unable to connect, please make sure you are connected to the internet",
  errorMessageNetwork: "network error. Please make sure you are connected to the internet.",
  errorRegister2: "error while creating your account. The login has already been used by another user.",
  errorRegister3: "error creating your account. Please make sure you are connected to the internet.",
  events: "events",
  firstname: "firstname",
  invalidForm: "some fields are not valid",
  language: "language",
  lastname: "lastname",
  login: "login",
  password: "password",
  phone: "phone",
  profile: "profile",
  register: "register",
  signIn: "sign in",
  signOut: "sign out",
  scan: "scan",
  seller: "i am a seller",
  settings: "settings",
  statistics: "statistics",
  successRegister: "Welcome to the BYT platform. \nYour account creation has been successfully completed. You can access your account using the login and password created",
  tickets: "tickets"
}

export { EN };