const FR = {
  administration: "administration",
  allEvents: "tous les événements",
  authentication: "authentification",
  birthday: "date de naissance",
  confirmPassword: "confirmation mot de passe",
  cancel: "annuler",
  createAccount: "créer un compte",
  code: "code",
  date: "date",
  delete: "supprimer",
  description: "déscription",
  email: "e-mail",
  errorMessageAuthentication: "erreur d'authentification. Cette session a expiré, veuillez vous reconnecter.",
  errorMessageLogin: "renseignez l'identifiant et le mot de passe",
  errorMessageLogin2: "identifiant ou mot de passe incorrect",
  errorMessageLogin3: "impossible de se connecter, veuillez vous assurer que vous êtes connectés à internet",
  errorMessageLockRevision: "des changements sur le même élément ont été faits à partir d'un autre poste. Veuillez recharger la page afin d'avoir la dernière version !",
  errorMessageNetwork: "erreur réseau. Veuillez vous assurer que vous êtes connectés à Internet.",
  errorRegister2: "erreur lors de la création de votre compte. L'identifiant a déjà été utilisé par un autre utilisateur.",
  errorRegister3: "erreur lors de la création de votre compte. Veuillez vous assurer que vous êtes connectés à Internet.",
  eventCode: "identification",
  eventName: "titre",
  events: "événements",
  firstname: "prénom",
  image: "image",
  invalidForm: "certains champs ne sont pas valides",
  language: "langue",
  lastname: "nom",
  login: "identifiant",
  modify: "modifier",
  myEvents: "mes événements",
  password: "mot de passe",
  phone: "téléphone",
  price: "prix",
  profile: "profile",
  register: "inscription",
  save: "enregister",
  signIn: "connexion",
  signOut: "déconnexion",
  scan: "scan",
  seller: "je suis un vendeur",
  settings: "paramètres",
  statistics: "statistiques",
  successRegister: "Bienvenue sur la plateforme BYT. Votre création de compte a été effectuée avec succès et vous pouvez y accéder en utilisant l'dentifiant et le mot de passe créés.",
  tag: "tag",
  tickets: "tickets",
  time: "heure",
  venue: "adresse"
};

export { FR };