const FR = {
  administration: "administration",
  allEvents: "tous les événements",
  authentication: "authentification",
  bankCard: "carte bancaire",
  birthday: "date de naissance",
  buyTicket: "achat d'un ticket",
  buyTicketDescriptionMessage: "effectuez le paiement en suivant les informations données ci-dessous et utilisez le code que vous recevrez pour obtenir un ticket.",
  confirmPassword: "confirmation mot de passe",
  cancel: "annuler",
  createAccount: "créer un compte",
  createCode: "générer un code",
  createTicketMessageSuccess: "votre ticket a été créé, veuillez le trouver dans l'espace 'Tickets' de votre compte.",
  code: "code",
  codeGenerationMessage: "vous venez de générer un code. Assurez-vous de transmettre ces informations à l'acheteur d'un ticket.",
  codeMarchand: "code marchand",
  date: "date",
  dateBuy: "date d'achat",
  delete: "supprimer",
  description: "déscription",
  email: "e-mail",
  errorMessageAuthentication: "erreur d'authentification. Cette session a expiré, veuillez vous reconnecter.",
  errorMessageLogin: "renseignez l'identifiant et le mot de passe",
  errorMessageLogin2: "identifiant ou mot de passe incorrect",
  errorMessageLogin3: "impossible de se connecter, veuillez vous assurer que vous êtes connectés à internet",
  errorMessageLockRevision: "des changements sur le même élément ont été faits à partir d'un autre poste. Veuillez recharger la page afin d'avoir la dernière version !",
  errorMessageNetwork: "erreur réseau. Veuillez vous assurer que vous êtes connectés à Internet.",
  errorMessageCodeGeneration: "une erreur s'est produite lors de la génération d'un code. Veuillez rééssayer ultérieurement.",
  errorRegister2: "erreur lors de la création de votre compte. L'identifiant a déjà été utilisé par un autre utilisateur.",
  errorRegister3: "erreur lors de la création de votre compte. Veuillez vous assurer que vous êtes connectés à Internet.",
  errorMessageTicketCreateWithCode: "une erreur est survenue lors de la création de votre ticket. Le code utilisé ne permet pas de créer ce ticket ou bien il a déjà été utilisé.",
  errorOccurredMessage: "une erreur est survenue lors de l'exécution de cette opération. Veuillez rééssayer ultérieurement.",
  errorMessageNotYourEvent: "vous n'avez pas le droit de scanner ce ticket. L'événement concerné appartient à un autre utilisateur.",
  eventCode: "identification",
  eventName: "titre",
  events: "événements",
  eventDetail: "détail de l'événement",
  firstname: "prénom",
  getTicket: "obtenir un ticket",
  image: "image",
  invalidForm: "certains champs ne sont pas valides",
  language: "langue",
  lastname: "nom",
  login: "identifiant",
  manualPayment: "utiliser un code",
  modify: "modifier",
  myEvents: "mes événements",
  noTicketEventFound: "aucun événement trouvé correspondant à ce ticket. Peut-être que l'événement a été supprimé",
  noUserFound: "aucun utilisateur correspondant à cette recherche", 
  numero: "numéro",
  operator: "opérateur",
  password: "mot de passe",
  phone: "téléphone",
  price: "prix",
  profile: "profile",
  register: "inscription",
  save: "enregister",
  signIn: "connexion",
  signOut: "déconnexion",
  scan: "scan",
  scanMessageSuccess: "la validation du ticket a été effectué avec succès. Veuillez informer le client que son ticket ne peut plus être utilisé.",
  search: "recherche",
  seller: "je suis un vendeur",
  settings: "paramètres",
  statistics: "statistiques",
  successRegister: "Bienvenue sur la plateforme BYT. Votre création de compte a été effectuée avec succès et vous pouvez y accéder en utilisant l'dentifiant et le mot de passe créés.",
  tag: "tag",
  tickets: "tickets",
  ticketUsed: "utilisé",
  time: "heure",
  userSearch: "recherche d'un utilisateur",
  userUpdateSuccess: "la mise à jour des informations a été effectuée avec succès.",
  validate: "valider",
  venue: "adresse"
};

export { FR };