const KI = {
  administration: "kugenzura",
  allEvents: "ibiteguwe vyose",
  authentication: "kwimenyekanisha",
  birthday: "italiki y'amavuko",
  confirmPassword: "subiramwo akajambo gahishijwe",
  cancel: "gusohoka",
  createAccount: "kwiyandikisha",
  code: "kode",
  date: "itariki",
  delete: "gufuta",
  description: "ibirimwo",
  email: "e-mail",
  errorMessageAuthentication: "ntitwashoboye kubamenya. Ni musubire mwinjire kuri runo rubuga ubugira kandi.",
  errorMessageLogin: "shiramwo login n'akajambo gahishijwe",
  errorMessageLogin2: "mwihenze kuri login canke kukajambo gahishijwe",
  errorMessageLogin3: "ntimushoboye kwinjira, nimurabe ko neza ko mwoba mufise umuhora wa Internet",
  errorMessageLockRevision: "hari ivyahinduriwe ahandi hantu. Nimusubire kwinjira gushasha mubone gusubira guhindura !",
  errorMessageNetwork: "ingorane ijanye n'umuhora. Ni murabe neza ko mwoba mufise umuhora wa Internet",
  errorRegister2: "habaye ingorane mukwiyandikisha kuri runo rubuga. Login mwakoresheje iramaze gukoreshwa n'uyundi muntu.",
  errorRegister3: "habaye ingorane, ntimwashoboye kwiyandikisha kuri runo rubuga. Ni murabe neza ko mwoba mufise umuhora wa Internet",
  eventCode: "nomero",
  eventName: "citwa",
  events: "ibiteguwe",
  firstname: "amatazirano",
  image: "isanamu",
  invalidForm: "hari ibisabwa mutujuje neza",
  language: "ururimi",
  lastname: "izina",
  login: "login",
  modify: "guhindura",
  myEvents: "ivyo nteguye",
  password: "akajambo gahishijwe",
  phone: "nomero ya terefone",
  price: "igiciro",
  profile: "profire",
  register: "kwiyandikisha",
  save: "ok",
  signIn: "kwinjira",
  signOut: "gusohoka",
  scan: "scan",
  seller: "umucuruzi",
  settings: "kuregera",
  statistics: "ibiharuro",
  successRegister: "Kaze ku rubuga BYT. Muhejeje kwiyandikisha, murashobora gutangura gukoresha ibiri hano, Mukinjira mukoresheje login n'akajambo gahishijwe mwakoresheje mukwiyandikisha.",
  tag: "tag",
  tickets: "ama tike",
  time: "amasaha",
  venue: "ikibanza"
}

export { KI };