const KI = {
  administration: "kugenzura",
  allEvents: "ibiteguwe vyose",
  authentication: "kwimenyekanisha",
  bankCard: "ikarata ya banki",
  birthday: "italiki y'amavuko",
  buyTicket: "kugura i tike",
  buyTicketDescriptionMessage: "ni murihe mukoreshe imihora yanditse hano musi hanyuma muze gukoresha i kode muza kurungikirwa mubone kuronka i tike.",
  confirmPassword: "subiramwo akajambo gahishijwe",
  cancel: "gusohoka",
  createAccount: "kwiyandikisha",
  createCode: "gusohora kode",
  createTicketMessageSuccess: "muhejeje gusohora i tike, murashobora kuyisanga muri 'Tike' ya BYT",
  code: "kode",
  codeGenerationMessage: "mugehejeje gusohora i kode. Ni muyirungikire uwaguze i tike",
  codeMarchand: "kode y'umudandaji",
  date: "itariki",
  dateBuy: "yaguzwe",
  delete: "gufuta",
  description: "ibirimwo",
  email: "e-mail",
  errorMessageAuthentication: "ntitwashoboye kubamenya. Ni musubire mwinjire kuri runo rubuga ubugira kandi.",
  errorMessageLogin: "shiramwo login n'akajambo gahishijwe",
  errorMessageLogin2: "mwihenze kuri login canke kukajambo gahishijwe",
  errorMessageLogin3: "ntimushoboye kwinjira, nimurabe ko neza ko mwoba mufise umuhora wa Internet",
  errorMessageLockRevision: "hari ivyahinduriwe ahandi hantu. Nimusubire kwinjira gushasha mubone gusubira guhindura !",
  errorMessageNetwork: "ingorane ijanye n'umuhora. Ni murabe neza ko mwoba mufise umuhora wa Internet",
  errorMessageCodeGeneration: "habaye ikibaze mugusohora i kode. Ni musubire mugerageze ubugira kandi",
  errorRegister2: "habaye ingorane mukwiyandikisha kuri runo rubuga. Login mwakoresheje iramaze gukoreshwa n'uyundi muntu.",
  errorRegister3: "habaye ingorane, ntimwashoboye kwiyandikisha kuri runo rubuga. Ni murabe neza ko mwoba mufise umuhora wa Internet",
  errorMessageTicketCreateWithCode: "ntibishoboye gukunda gusohora i tike. Kode mwakoresheje siyo canke iramaze gukoreshwa.",
  errorOccurredMessage: "hari ikibazo cabaye, ntidushoboye kuronka inyishu y'ivyo murondera. Murasubira mugerageze hanyuma",
  errorMessageNotYourEvent: "nta burenganzira mufise bwo gu scanna ino tike. Igiteguwe cashizweho n'uyundi muntu atari mwebwe.",
  eventCode: "nomero",
  eventName: "citwa",
  events: "ibiteguwe",
  eventDetail: "vyinshi ku giteguwe",
  firstname: "amatazirano",
  getTicket: "koronka i tike",
  image: "isanamu",
  invalidForm: "hari ibisabwa mutujuje neza",
  language: "ururimi",
  lastname: "izina",
  login: "login",
  manualPayment: "ukoresheje kode",
  modify: "guhindura",
  myEvents: "ivyo nteguye",
  noTicketEventFound: "nta giteguwe kijanye n'ino tike gihari. Kumbure ico giteguwe gishobora kuba carafuswe",
  noUserFound: "nta muntu n'umwe dushobora gutora afise ibi birangwa",
  numero: "nomero",
  operator: "umuhora",
  password: "akajambo gahishijwe",
  phone: "nomero ya terefone",
  price: "igiciro",
  profile: "profire",
  register: "kwiyandikisha",
  save: "ok",
  signIn: "kwinjira",
  signOut: "gusohoka",
  scan: "scan",
  scanMessageSuccess: "muhejeje gu scanna i tike. Ni mubwire nyene iyo tike ko adasubira kuyikoresha.",
  search: "kurondera",
  seller: "umucuruzi",
  settings: "kuregera",
  statistics: "ibiharuro",
  successRegister: "Kaze ku rubuga BYT. Muhejeje kwiyandikisha, murashobora gutangura gukoresha ibiri hano, Mukinjira mukoresheje login n'akajambo gahishijwe mwakoresheje mukwiyandikisha.",
  tag: "tag",
  tickets: "ama tike",
  ticketUsed: "yakoreshejwe",
  time: "amasaha",
  userSearch: "kurondera umuntu",
  userUpdateSuccess: "muhejeje guhindura ibirangwa",
  validate: "kwemeza",
  venue: "ikibanza"
}

export { KI };