const KI = {
  administration: "kugenzura",
  authentication: "kwimenyekanisha",
  birthday: "italiki y'amavuko",
  confirmPassword: "subiramwo akajambo gahishijwe",
  cancel: "gusohoka",
  createAccount: "kwiyandikisha",
  code: "kode",
  email: "e-mail",
  errorMessageAuthentication: "ntitwashoboye kubamenya. Ni musubire mwinjire kuri runo rubuga ubugira kandi.",
  errorMessageLogin: "shiramwo login n'akajambo gahishijwe",
  errorMessageLogin2: "mwihenze kuri login canke kukajambo gahishijwe",
  errorMessageLogin3: "ntimushoboye kwinjira, nimurabe ko neza ko mwoba mufise umuhora wa Internet",
  errorMessageNetwork: "ingorane ijanye n'umuhora. Ni murabe neza ko mwoba mufise umuhora wa Internet",
  errorRegister2: "habaye ingorane mukwiyandikisha kuri runo rubuga. Login mwakoresheje iramaze gukoreshwa n'uyundi muntu.",
  errorRegister3: "habaye ingorane, ntimwashoboye kwiyandikisha kuri runo rubuga. Ni murabe neza ko mwoba mufise umuhora wa Internet",
  events: "ibiteguwe",
  firstname: "amatazirano",
  invalidForm: "hari ibisabwa mutujuje neza",
  language: "ururimi",
  lastname: "izina",
  login: "login",
  password: "akajambo gahishijwe",
  phone: "nomero ya terefone",
  profile: "profire",
  register: "kwiyandikisha",
  signIn: "kwinjira",
  signOut: "gusohoka",
  scan: "scan",
  seller: "umucuruzi",
  settings: "kuregera",
  statistics: "ibiharuro",
  successRegister: "Kaze ku rubuga BYT. Muhejeje kwiyandikisha, murashobora gutangura gukoresha ibiri hano, Mukinjira mukoresheje login n'akajambo gahishijwe mwakoresheje mukwiyandikisha.",
  tickets: "ama tike"
}

export { KI };